[package]
name = "theia_update_plugins"
version = "0.1.0"
authors = ["Tice Cosmos <tice@139.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-http-request = "0.2"
env_logger = "0.7"
serde_json = "1.0"
log = "0.4"
quick-xml = "0.18"
rand = {version = "0.7", features = ["small_rng"]}
structopt = "0.3"
toml = "0.5"
zip = "0.5"
