[package]
name = "theia_update_plugins"
version = "0.2.0"
authors = ["Tice Cosmos <tice@139.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5"
env_logger = "0.7"
log = "0.4"
quick-xml = "0.18"
reqwest = "0.10"
serde_json = "1.0"
structopt = "0.3"
tokio = { version = "0.2", features = ["full"] }
toml = "0.5"
zip = "0.5"
