[package]
name = "theia_update_plugins"
version = "0.2.4"
authors = ["Tice Cosmos <tice@139.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6"
chrono = "0.4"
env_logger = "0.7"
futures = "0.3"
log = "0.4"
quick-xml = "0.18"
serde_json = "1.0"
surf = { version = "1.0", default-features = false, features = ["native-client"] }
structopt = "0.3"
toml = "0.5"
zip = "0.5"
